Bugfix/85/tab in modal form
vstrabko/exadelSandboxFE pull request #49
Opened 2021-11-04 09:01 UTC by mhasilau

on modal wondow TAB is not wors at all, because for that u need to get conponents from DOM

2021-11-04 09:03 UTC, vstrabko approved these changes

2021-11-04 10:08 UTC, mhasilau commented
Do not merge!

2021-11-04 15:36 UTC, PaulRomanov approved these changes

2021-11-09 07:12 UTC, vstrabko requested changes
Still in progress

2021-11-09 07:55 UTC, vstrabko approved these changes

2021-11-09 09:12 UTC, PaulRomanov commented
I suppose everything is fine

2021-11-09 09:17 UTC, Nicolai-boiko approved these changes

2021-11-09 09:21 UTC, merged