Feature/90/sandbox form multiselect search
vstrabko/exadelSandboxFE pull request #52
Opened 2021-11-09 12:10 UTC by Dmitruk89

<img width="994" alt="Снимок экрана 2021-11-09 в 13 17 57" src="https://user-images.githubusercontent.com/57582285/140921478-8d69fa24-856c-4238-a87e-dd0a6c909c7d.png">
1. replace standard multi-select fields of create-sandbox page with searchable multi-select
2.  fix search filter in multi-select.

2021-11-09 12:19 UTC, Nicolai-boiko approved these changes

2021-11-09 13:57 UTC, Nicolai-boiko requested changes

2021-11-09 13:57 UTC, Nicolai-boiko commented on src/app/app-routing.module.ts
delete import { CandidateListComponent } from './components/candidate/candidate-list/candidate-list.component';

2021-11-09 13:59 UTC, Nicolai-boiko approved these changes

2021-11-09 16:59 UTC, PaulRomanov commented
looks without errors

2021-11-09 17:00 UTC, PaulRomanov approved these changes

2021-11-10 06:54 UTC, vstrabko approved these changes
Looks good. Just 2 small comments

2021-11-10 06:54 UTC, vstrabko commented on src/app/components/candidate/multiselect-search/multiselect-search.component.scss
> +    color: rgba(0,0,0,0.6);
color should be in colors scss file :)

2021-11-10 06:54 UTC, vstrabko commented on src/app/pages/create-sandbox-page/create-sandbox-page.component.scss
> +  background-color: rgba(0,0,0,.04);
Same here

2021-11-10 09:15 UTC, Dmitruk89 commented on src/app/components/candidate/multiselect-search/multiselect-search.component.scss
> +    color: rgba(0,0,0,0.6);
fixed

2021-11-10 09:16 UTC, merged