Feature/104/integration of submitting candidate form
vstrabko/exadelSandboxFE pull request #57
Opened 2021-11-16 13:49 UTC by Nicolai-boiko

![изображение](https://user-images.githubusercontent.com/72386426/141997264-1f8a616a-0fb6-4d33-ab39-04c9c5a08700.png)

2021-11-16 14:02 UTC, vstrabko requested changes

2021-11-16 14:02 UTC, vstrabko commented on src/app/pages/home-page/home-page.component.scss
> +}
This style here becomes global after using ng:deep.
Are you sure it is not affecting other places?

2021-11-16 14:02 UTC, vstrabko commented on src/app/pages/home-page/home-page.component.ts
> +  sandboxChosen: any = {};
Change `any` here

2021-11-16 15:11 UTC, vstrabko approved these changes

2021-11-16 15:23 UTC, rastorc3v requested changes

2021-11-16 15:23 UTC, rastorc3v commented on src/app/components/candidate-request/candidate-request.component.html
> +      <textarea formControlName="professionaCertificates" [cdkTextareaAutosize] class="skills_textarea" matInput></textarea>
can you fix class name here and in the styles to use dash instead of underline please

2021-11-16 15:23 UTC, rastorc3v commented on src/app/models/resource.model.ts
> +    return JSON.stringify(this);
looks like to string =) not to json

2021-11-16 15:23 UTC, rastorc3v commented on src/app/models/sandbox.model.ts
> +import { IdName } from './id-name.model';
Can you rename id-name.* to something more meaningful please

2021-11-16 15:23 UTC, rastorc3v commented on src/app/pages/home-page/home-page.component.html
> +    <div [style.display]="sandboxSelect.value ? 'block' : 'none'" class="sandbox-interviews_container">
Replace underline wtih dash please

2021-11-16 15:23 UTC, rastorc3v commented on src/app/pages/home-page/home-page.component.ts
> +      const sandCh = this.sandboxes.find((item: Sandbox) => item.name === value);
rename sandCh to something meaningful please, like _sandboxChosen

2021-11-16 15:23 UTC, rastorc3v commented on src/app/services/candidate-context.service.ts
> +  title = '';
add modificators everywhere please

2021-11-16 15:23 UTC, rastorc3v commented on src/app/services/candidate-context.service.ts
> +      this.get().subscribe((data: candidateRequestData[]): void =>
You can use 
`dataArray = [...dataArray, ...data]` instead of forEach

2021-11-16 15:23 UTC, rastorc3v commented on src/app/services/candidate-context.service.ts
> +  getData(dataArray: any[], currentUrl: string): any[] {
please, change any[] type to something else. According to code below it should be candidateRequestData[]

2021-11-17 10:13 UTC, rastorc3v approved these changes

2021-11-17 10:18 UTC, mhasilau approved these changes

2021-11-17 10:19 UTC, merged