Feature/120/integretion create and edit sandbox
vstrabko/exadelSandboxFE pull request #68
Opened 2021-11-25 13:40 UTC by Nicolai-boiko

![изображение](https://user-images.githubusercontent.com/72386426/143451752-b90c7c91-ac40-4ac4-8271-d389f5ba45af.png)

2021-11-25 14:12 UTC, mhasilau commented on src/app/components/candidate-request/candidate-request.component.html
> +      </mat-form-field> -->
comments

2021-11-25 14:12 UTC, mhasilau commented on src/app/pages/create-sandbox-page/create-sandbox-page.component.html
> +
leave one space line

2021-11-25 14:12 UTC, mhasilau commented on src/app/pages/create-sandbox-page/create-sandbox-page.component.html
> +</div>
add line

2021-11-25 14:12 UTC, mhasilau commented on src/app/pages/create-sandbox-page/create-sandbox-page.component.html
> +
leave one space line

2021-11-25 14:12 UTC, mhasilau commented on src/app/pages/create-sandbox-page/create-sandbox-page.component.scss
> +}
add line

2021-11-25 14:12 UTC, mhasilau commented on src/app/services/api.service.ts
>      // ...optionally return a default fallback value so app can continue (pick one)
we need this comment?

2021-11-26 07:04 UTC, mhasilau approved these changes

2021-11-26 09:22 UTC, PaulRomanov approved these changes

2021-11-26 09:53 UTC, vstrabko reviewed
Why so many files were deleted?

2021-11-26 09:53 UTC, vstrabko commented on src/app/components/candidate-request/candidate-request.component.html
> +          loc.name : ''">{{loc !==
Are you sure this part of the code is run though prettier?

2021-11-26 11:58 UTC, rastorc3v requested changes
Why did you delete some components (candidate-record, list, module)?
If you want to create a Pipe for filtering, please do it in another PR (this is already big anough =))

2021-11-26 11:58 UTC, rastorc3v commented on src/app/components/candidate-request/candidate-request.component.html
> +        class="motivation_textarea"
Rename class please to use - instead of _

2021-11-26 11:58 UTC, rastorc3v commented on src/app/components/candidate-request/candidate-request.component.html
> +            *ngFor="let lang of sandboxChosen.languages"
it's easier to filter list and remove nulls than add ? : expressions. I would like to see Pipe for this purpose. Can you create one? It's not complicated (spoiler)

2021-11-26 11:58 UTC, rastorc3v commented on src/app/components/candidate-request/candidate-request.component.html
> +            *ngFor="let skill of sandboxChosen.stackTechnologies"
You can apply pipe from previous comment here

2021-11-26 11:58 UTC, rastorc3v commented on src/app/services/api.service.ts
> -  public create(resource: Partial<T> & { toJson: () => T }): Observable<any> {
api service is super common fiture. Please verify that you didn't break anything by these changes before the merge.

2021-11-26 11:58 UTC, rastorc3v commented on src/app/services/api.service.ts
> -      // A client-side or network error occurred. Handle it accordingly.
I prefer comments to leave here. It would be useful in the future.

2021-11-26 14:27 UTC, rastorc3v requested changes

2021-11-26 14:27 UTC, rastorc3v commented on src/app/pages/create-sandbox-page/create-sandbox-page.component.ts
> +          this.sandboxChosen.stackTechnologies && this.sandboxChosen.stackTechnologies[0] !== null
Create function which do the same logic for each object

2021-11-29 09:09 UTC, rastorc3v approved these changes

2021-11-29 09:33 UTC, merged