Feature/105 a/integration of getting list of sandboxes
vstrabko/exadelSandboxFE pull request #69
Opened 2021-11-26 16:17 UTC by PaulRomanov

![image](https://user-images.githubusercontent.com/60575337/143608396-df68f360-28ae-44f0-b512-744967732a9e.png)

2021-11-29 07:22 UTC, rastorc3v requested changes

2021-11-29 07:22 UTC, rastorc3v commented on src/app/pages/sandbox-list-page/sandbox-list-page/sandbox-data-source.ts
> +  // eslint-disable-next-line
Why did you use it?

2021-11-29 07:22 UTC, rastorc3v commented on src/app/pages/sandbox-list-page/sandbox-list-page/sandbox-list-page.component.ts
> +/* eslint-disable @typescript-eslint/explicit-module-boundary-types */
Remove

2021-11-29 07:22 UTC, rastorc3v commented on src/app/pages/sandbox-list-page/sandbox-list-page/sandbox-list-page.component.ts
> +      .subscribe((data: any) => {
Replace 'any' with interface please

2021-11-29 07:22 UTC, rastorc3v commented on src/app/pages/sandbox-list-page/sandbox-list-page/sandbox-list-page.component.ts
> +        console.log('data sort', data);
Remove it please

2021-11-29 07:22 UTC, rastorc3v commented on src/app/pages/sandbox-list-page/sandbox-list-page/sandbox-data-source.ts
> +  // eslint-disable-next-line
Remove

2021-11-29 07:22 UTC, rastorc3v commented on src/app/pages/sandbox-list-page/sandbox-list-page/sandbox-list-page.component.ts
> +    this.paginator.page.pipe(tap(() => this.loadSandboxesPage())).subscribe((data: any) => {
The same, replace any

2021-11-29 07:32 UTC, mhasilau commented on src/app/components/popup-choose-the-time/time/time.component.scss
> +  border: solid 1px black;
add constant color

2021-11-29 09:06 UTC, PaulRomanov commented on src/app/pages/sandbox-list-page/sandbox-list-page/sandbox-data-source.ts
> +  // eslint-disable-next-line
Otherwise I could not solve the problem

2021-11-29 09:08 UTC, PaulRomanov commented on src/app/pages/sandbox-list-page/sandbox-list-page/sandbox-list-page.component.ts
> +/* eslint-disable @typescript-eslint/explicit-module-boundary-types */
The problem solved

2021-11-29 09:10 UTC, PaulRomanov commented on src/app/pages/sandbox-list-page/sandbox-list-page/sandbox-data-source.ts
> +  // eslint-disable-next-line
Otherwise I could not solve the problem

2021-11-29 10:01 UTC, PaulRomanov commented on src/app/components/popup-choose-the-time/time/time.component.scss
> +  border: solid 1px black;
The problem solved

2021-11-30 08:11 UTC, PaulRomanov commented on src/app/pages/sandbox-list-page/sandbox-list-page/sandbox-list-page.component.ts
> +      .subscribe((data: any) => {
fix

2021-11-30 08:12 UTC, PaulRomanov commented on src/app/pages/sandbox-list-page/sandbox-list-page/sandbox-list-page.component.ts
> +        console.log('data sort', data);
fix

2021-11-30 08:12 UTC, PaulRomanov commented on src/app/pages/sandbox-list-page/sandbox-list-page/sandbox-list-page.component.ts
> +    this.paginator.page.pipe(tap(() => this.loadSandboxesPage())).subscribe((data: any) => {
fix

2021-11-30 10:11 UTC, rastorc3v approved these changes

2021-11-30 10:54 UTC, Nicolai-boiko approved these changes

2021-11-30 13:27 UTC, merged